# directory where database and logs are created
output_dir: output/

console_log_level: INFO

default_fuzzy_search: true

host: localhost
port: 8000

# AI features
# Disable it if you don't want to run LLM locally
enable_ai: true
